### ISSUE TITLE
Error processing transaction. SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Kenander12** [IBM/global-financing-blockchain#13]
Hello!

I followed the tutorial but I am having problems when running the app. The error shown in the image appears, and I cannot register or transact.

Thanks in advance for your help.

Awaiting.

![Captura de tela de 2019-09-18 18-06-35](https://user-images.githubusercontent.com/16767091/65186316-c9814d80-da3f-11e9-8866-3423e7e9d95e.png)

**Comment by sandhya-nayak** [comment]
@Kenander12 Created pull request #14 with the fix.
Kindly try it out and close this issue if the changes resolve your issue, else comment with any other issues you face.
Thanks.
