### ISSUE TITLE
Error getting metadata for smart contract globalfinancing

### ISSUE THREAD

**Issue by andrewyuau** [IBM/global-financing-blockchain#3]
Hi,

I ran this today and I received an error when I tried to instantiate the contract. The error message is "Error getting metadata for smart contract globalfinancing, please ensure this smart contract is depending on at least fabric-contract@1.4.0-beta2". See screenshot below for details.

![image](https://user-images.githubusercontent.com/14987623/50580293-d6094a00-0ea0-11e9-8334-9c25f862b388.png)

**Comment by raheelzubairy** [comment]
@andrewyuau I just went successfully through the pattern and application, and made updates here: https://github.com/IBM/global-financing-blockchain/commit/1cb31cc72392c5669bc81f3357bf078b44392429 including updating the contract libraries to "1.4.0-beta2"

Could you try and see if this corrects your issue?  You should see a notification for `successfully instantiated smart contract`

**Comment by andrewyuau** [comment]
Thank you for the updates, I now see the notification for a successful instantiation, although I still see the same error message. The web app is working fine.

**Comment by raheelzubairy** [comment]
@andrewyuau are you still seeing the error message?
